import type { Metadata } from 'next'
import './globals.css'
import localFont from 'next/font/local'

const iranSans = localFont({
  src: '../public/fonts/iranSans.ttf',
  variable: '--font-iranSans',
})
const iranSansBold = localFont({
  src: '../public/fonts/iranSansBold.ttf',
  variable: '--font-iranSansBold',
})
const roboto = localFont({
  src: '../public/fonts/roboto.ttf',
  variable: '--font-roboto',
})

export const metadata: Metadata = {
  title: 'Hamyar Zaban',
  description: 'Generated by mahdi',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="fa" dir='rtl'>
      <body className={`${iranSans.variable} ${iranSansBold.variable} ${roboto.variable} ${iranSans.className}`}>{children}</body>
    </html>
  )
}
