import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import localFont from 'next/font/local'
const inter = Inter({ subsets: ['latin'] })
const iranSans = localFont({
  src: '../public/fonts/iranSans.ttf',
  variable: '--font-iranSans',


})

export const metadata: Metadata = {
  title: 'Hamyar Zaban',
  description: 'Generated by mahdi',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" dir='rtl'>
      <body className={iranSans.variable}>{children}</body>
    </html>
  )
}
